version: "2"
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.json
      extensions:
        - .js
        - .mjs
exclude_patterns:
  - ".gitignore"
  - ".jshintrc"
  - ".babelrc"
  - ".codeclimate.yml"
  - ".eslintrc.json"
  - ".jsdoc.json"
  - ".npmignore"
  - ".travis.yml"
  - "yarn.lock"
  - "tests/"
  - ".vscode/"
  - "LICENSE"
  - "README.md"
  - "docs/"
  - "package.json"
  - "gulpfile.js"
